spring.application.name=WomenSecurity
server.port=8080
spring.data.mongodb.database=test
spring.data.mongodb.uri=mongodb+srv://nileshgoyal624:nilesh774@cluster0.ijna3ey.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0
