spring.application.name=WomenSecurity
server.port=8080
spring.data.mongodb.database=WomenSecurity
spring.data.mongodb.uri=mongodb+srv://hardikgupta8080:12345@cluster0.veuwe05.mongodb.net/women_security?retryWrites=true&w=majority