spring.application.name=WomenSecurity
server.port=8080
spring.data.mongodb.database=WomenSecurity
spring.data.mongodb.uri=mongodb+srv://nileshgoyal624:nilesh774@cluster0.ijna3ey.mongodb.net/women_security?retryWrites=true&w=majority&appName=Cluster0
